mode: 'textual' # 'textual' or 'visual'
is_analysis: false
is_runtime_analysis: true
is_quiet: true

recording_filepath: /mnt/data/vrg/spetlrad/data/periodic/datasets/propeller_dataset/camera-angle-0/recording_2023-11-30_13-20-18_7950rpm.raw
analysis_filepath: /mnt/data/vrg/spetlrad/data/periodic/experiments/test/propeller_dataset-camera-angle-0_recording_2023-11-30_13-20-18_7950rpm.h5
tensorboard_log_file: tb_log.tfevents

simulate_real_time: false

height: 720
width: 1280

start_us: 0
end_us: 0

acc: 4000 #40000
fps: 25

temporal_stride: 1

k_min: 6
k_max: 6

alpha_of_burst_std: 0.9
alpha_interarrival_time: 0.0001
alpha_interarrival_time_window_size: 5000
min_interarrival_time: 0.5
max_rate: 720.0
T_min: 100

min_E_x_of_std: 3300 #us
max_E_x_of_std: 33000 #us

# Standard-deviation thresholds
max_burst_std_per_cent: 20.0

polarity: 's'   # 'n' or 'p' or 'b' for both or 's' for simultaneous

scale_down_factor: 1.0
rotation_angle: 105.0

compute_pitch_roll: true
pitch_roll_estimation_alpha: 0.0001
pitch_gt: 1.0
pitch_scaler: 1.0 # a scalar that multiplies the pitch estimation to provide angles in degrees